app/views/code_of_conduct/index.html
This can be viewed online at https://www.globaldiversitycfpday.com/code-of-conduct
=> Adding escalation process to Code of Conduct

email_templates/organiser_email_templates/1-thanks-for-signing-up.html, email_templates/organiser_email_templates/2-Inspiration.html, email_templates/organiser_email_templates/3-travel-tips.html, email_templates/organiser_email_templates/4-accessability.html, email_templates/organiser_email_templates/5-two-days-to-go.html, email_templates/organiser_email_templates/README.txt
These are a series of email template which organisers can use to send to their attendees which are aimed at keeping your attendees engaged, excited and reminded about the amazing workshop you've put together for them.
Ideally one of these will be sent out every week from now until Feb 3rd.
Within `email_templates/organiser_email_templates/README.txt` there are some instructions on how what needs to be filled in, in each of the 5 emails templates.
Below are previews of each of the templates
**Template: 1-thanks-for-signing-up.html**
**Template: 2-inspiration.html**
**Template: 3-travel-tips.html**
**Template: 4-accessibility.html**
**Template: 5-two-days-to-go.html**
=> Local workshop organiser email templates

email_templates/company-promo-mailshot/glasgow-and-edinburgh-template.html
Promo email shot that can be sent to companies to distribute internally to help reach potential attendees.
=> Glasgow and Edinburgh workshop promo email for companies to distribute internally

app/views/preparation/index.html.erb, email_templates/organiser_email_templates/3-travel-tips.html, email_templates/organiser_email_templates/4-accessability.html, email_templates/organiser_email_templates/README.txt
Noticed this one, so did a global search and found a few more. Is the file rename going to break anything?
=> typo: accessability => accessibility

app/views/code_of_conduct/index.html.erb
[Kim Crayton](https://twitter.com/@KimCrayton1) and I have rewrote the Code of Conduct.
Apologies for the last minute nature of this. Any feedback is much appreciated and we'll aim to release this on Thursday.
The reason for this is to change the structure of the Code of Conduct by
* Positively explaining what we are trying to achieve
* Set an expectation about the vast diversity of people may be encountered and to use this as a positive opportunity.
* Set the bar for inappropriate behaviour, rather than have organisers being quizzed or argued with about the definition of harassment.
`"We are all here to learn and grow. This event, being a professional and safe environment, is not the appropriate venue to question individuals on their underrepresented status."`
=> Code of Conduct rewrite

README.md
This PR adds some more information to the README. I had to jump through a couple of hoops to get this running, and I think this info reduces the barrier to entry.
=> add prerequisite for postgres and add some titles

app/views/organise/index.html.erb
This PR is intended to give a clearer picture of what is expected of organisers.
Emphasising:
* 1 workshop per city (work together folks)
* Representation Matters in each Workshop Team
* It is up to Workshop Teams to promote their workshop
=> Updating Organiser Page text

app/assets/stylesheets/bootstrap_customisations.css.scss, app/views/layouts/application.html.erb
This PR addresses :octocat: [Issue 22](https://github.com/JiggyPete/global-diversity-cfp-day-site/issues/22)
**Before:**
**After:**
=> Improve colour contrast of site

README.md, db/seeds.rb
These are small seeds that add a very simple workshop, and attach it to a user. I found these made developing a little easier as you don't have to create a user every time you want to log in.
=> Add seed for a user and a workshop

app/controllers/users_controller.rb, app/controllers/workshops_controller.rb, app/models/user.rb, app/models/workshop.rb, app/views/admin/workshops/index.html.erb, app/views/email_templates/1_thanks_for_signing_up.html.erb, app/views/email_templates/2_inspiration.html.erb, app/views/events/show.html.erb, app/views/workshops/_display_user.html.erb, app/views/workshops/show.html.erb, spec/models/user_spec.rb, spec/models/workshop_spec.rb
Closes https://github.com/JiggyPete/global-diversity-cfp-day-site/issues/30
=> Multiple organisers  issue 30

app/controllers/admin/users_controller.rb, app/helpers/application_helper.rb, app/views/admin/users/edit.html.erb, app/views/admin/users/index.html.erb, config/routes.rb, spec/helpers/application_helper_spec.rb
This PR now allows admin users to edit & update any users details, and also remove them from the system.
=> Adding admin user management

app/views/homepage/_online-workshops.html.erb, config/locales/es.yml, config/locales/views/en.homepage.yml, config/locales/views/es.code_of_conduct.yml, config/locales/views/es.homepage.yml
Leaving as a Draft while I get a couple of reviews.
I think we wouldn't need to quote strings when using `¡` and `¿`, but I didn't boot Rails to see if the translations were valid.
=> Adds Spanish translations

app/views/workshops/_invite_user.html.erb
=> Fixes a typo.

config/continents.yml
=> Adds my pronouns.

config/continents.yml
Can I continue to add speaker information as they come in?
=> Add Asia speaker information

config/continents.yml
=> Adds Suze's message.

config/continents.yml
=> Adds Suze Shardlow's bio.

app/views/homepage/_announcement_reschedule_2021.html.erb, config/locales/views/en.reschedule_2021.yml, config/locales/views/es.reschedule_2021.yml
Translates the reschedule announcement to Spanish
=> Translates reschedule Announcement

config/continents.yml
=> Removes Amr's profile from the website.

config/continents.yml
=> Adds Jessica Jordan to the website.
